### ISSUE TITLE
iOS 16.1 Crash 

### ISSUE THREAD

**Issue by AnneBlair** [hughkli/Lookin#12]
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/17793074/209604778-54c9896c-53c0-4087-93b4-1e151799ecca.png">

A necessary crash occurred on the iOS 16 system, xcode: 14.1

Device: iPhone 14 Pro Max. iPhone 14 Pro, iPhone 13 Mini will crash

**Comment by hughkli** [comment]
把 LookinServer 升级到最新的 1.1.3 即可。
