### ISSUE TITLE
很多变量是没有对象名称的。

### ISSUE THREAD

**Issue by Ucself** [hughkli/Lookin#13]
![image](https://user-images.githubusercontent.com/5546554/219326473-c87c3887-7df3-45cb-93fc-fedd5f0c19de.png)
很多变量是没有对象名称的，对象是通过如下代码定义：

    lazy var nameLab = UILabel()
    lazy var avatarIV = UIImageView()
    lazy var bubbleBgIV = UIImageView()
    lazy var contentBgView = UIView()
    lazy var indicator = UIActivityIndicatorView.init(activityIndicatorStyle: .gray)
    lazy var failIcon = UIImageView(image: UIImage(named: "message_send_failed"))

请问这有办法解决吗

**Comment by YmiroS** [comment]
我也遇到了同样的问题,Swift 使用 iVar 不太好用了, 判断类型会为空, 最近尝试了使用Mirror(reflecting:)可以找到对应的属性。

**Comment by aiqinxuancai** [comment]
看看是否保护了method_exchangeImplementations等函数禁止被hook，这是会影响的

**Comment by sushushu** [comment]
swift的类是会看不到的

**Comment by hughkli** [comment]
用最新的 LookinServer，然后加个 “Swift” Subspec，应该就可以看到了。我试了是没问题的：
![image](https://github.com/hughkli/Lookin/assets/15059475/5272e33c-6690-4eac-9bcd-0283cbee47aa)
![image](https://github.com/hughkli/Lookin/assets/15059475/538a7945-2d0b-441f-a567-80dc9c3a525a)

 pod 'LookinServer',  :subspecs => ['Swift']
