### ISSUE TITLE
关于调试台

### ISSUE THREAD

**Issue by Yrocky** [hughkli/Lookin#15]
目前的调试台只支持ui框架下的对象的调试，对于非ui对象不能进行调试。
<img width="397" alt="image" src="https://user-images.githubusercontent.com/8760136/225522758-91b29be9-ed47-44c8-8d13-7bf5557157fc.png">

所以，我的问题是，这个功能目前不支持么，如果支持有什么开关或者使用教程么；如果不支持，这个有计划支持么。

**Comment by hughkli** [comment]
其实是可以的，只是比较麻烦（我当初没有想出更好的交互方法）。

按照你的截图，返回 viewModel 对象后，你就可以点击绿色的菜单，然后选中返回的 viewModel 对象实例。
![image](https://github.com/hughkli/Lookin/assets/15059475/2280044d-9223-41da-8a15-a06e81cac7f2)
