### ISSUE TITLE
更新之后模拟器上不能用

### ISSUE THREAD

**Issue by xuchulei** [hughkli/Lookin#2]
一直显示尚未发现任何iOS App

**Comment by hughkli** [comment]
把集成了 LookinServer 的 iOS 项目 Run 一下，然后右下角控制台里搜索 "LookinServer" 看看结果是什么？

**Comment by wulikanhua66** [comment]
一直显示尚未发现任何iOS App,   Run 以后，然后右下角控制台里搜索 "LookinServer" 啥玩意没有

**Comment by hughkli** [comment]
那说明你的 iOS App 没有成功集成 LookinServer。
你预期是通过什么方式集成 LookinServer 的？CocoaPods？

**Comment by JIAZoro** [comment]
怎么退回到旧版本，旧版本还能用

**Comment by saltcoffee** [comment]
断点方式，也是找不到任何iOS app

**Comment by SavelySakun** [comment]
Breakpoint method doesn't work on 1.0.1 🌝

**Comment by hughkli** [comment]
对，符合预期，1.0.1 不再支持断点方式，原因是我不懂咋弄，具体包括：
1）不知道怎么打 .xcframework（之前只需要打 .framework）
2）不知道怎么写 breakpoint expr 实现“从 xcframework 里加载对应的文件”

你可以：
1）回退到旧的 1.0.0 版本：https://cdn.lookin.work/release/Lookin-1-0-0.zip 
2）等待某天我有时间了研究一下怎么弄
3）等待某个大神研究出来怎么弄，然后提个 merge request……
