### ISSUE TITLE
关于 lookin 客户端崩溃

### ISSUE THREAD

**Issue by Rock-Connotation** [hughkli/Lookin#20]
电脑信息： M2 Ventura 13.4，Xcode 14.1
情况描述：在未运行导入了 lookin 的项目时，lookin 客户端可正常运行并在桌面上展示“找不到你的app？”的界面。但在运行项目之后 lookin 就崩溃了。

**Comment by hughkli** [comment]
你可以先尝试把 LookinServer 更新到最新版本（好像是  1.1.8？），如果仍然可以稳定重现这个 Bug 的话，你可以有两种 Debug 方式：

1. 在你的 iOS App 中，通过代码发送一个名为 “Lookin_Export“ 的 NSNotification，这可以将你当前的 iOS 界面数据导出为一个 Lookin 文件，然后你把这个文件发给我，我试试看能不能重现。

2. 你在 Github 上直接把 Lookin 源码下载下来、本地编译，然后看看具体是 Crash 在了哪一行。
