### ISSUE TITLE
需要兼容一下 Xcode 15 和 iOS 17

### ISSUE THREAD

**Issue by LisonFan** [hughkli/Lookin#21]
```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UIGraphicsBeginImageContext() failed to allocate CGBitampContext: size={0, 0}, scale=3.000000, bitmapInfo=0x2002. Use UIGraphicsImageRenderer to avoid this assert.'
```

使用 `UIGraphicsBeginImageContext` 生成图片时，`size` 不能输入 `0,0` 了

**Comment by hughkli** [comment]
好的，我尽快处理一下

**Comment by WFlame314** [comment]
+1，一用LookIn刷新到一半就崩溃，尽快适配一下吧

**Comment by hughkli** [comment]
<img width="1662" alt="截屏2023-09-21 00 14 40" src="https://github.com/hughkli/Lookin/assets/15059475/c4baa720-874f-4061-8bc3-cbad10336466">

@WFlame314 @LisonFan Crash 的堆栈是上图这个不？

**Comment by hughkli** [comment]
刚刚发了 LookinServer v1.2.1，应该修复了，你们试试

**Comment by WFlame314** [comment]
![assert](https://github.com/hughkli/Lookin/assets/75198079/28eba5a1-3098-415c-8d73-16d879c5be46)
看起来还是会被assert，端上有些视图会存在size为(0,0)的情况

**Comment by hughkli** [comment]
@WFlame314 这。。。这么奇怪吗？理论上应该可以被上面的 if (pixelWidth <= 0 || pixelHeight <= 0) { 给拦住才对呀
![screenshot-20230921-133406](https://github.com/hughkli/Lookin/assets/15059475/c37d91eb-8ab9-4ef6-b3c3-11239136eaa2)

**Comment by WFlame314** [comment]
<img width="899" alt="Snipaste_2023-09-21_13-46-42" src="https://github.com/hughkli/Lookin/assets/75198079/3117a918-bb5f-48d6-9abd-3df21cbf7120">
po了一下，更奇怪了。。。

**Comment by hughkli** [comment]
可能是这个  CALayer 应用了一个 transform 导致 frame 和 bounds 不一样，我晚上有时间时加个额外的保护…

**Comment by hughkli** [comment]
发了 1.2.2，应该彻底修了这个，试试。
