### ISSUE TITLE
[Question] Why we can't integrate Lookin into release build configuration?

### ISSUE THREAD

**Issue by samsung-ga** [hughkli/Lookin#24]
I'm wondering why we can't integrate Lookin into release build configuration. Is it because of security?
I just want to put it in my Xcode SPM settings and use it, would that be a problem?

**Comment by hughkli** [comment]
Three  reasons:
1.  Your  online  users  or  other  companies'  programmers  can  operate  your  App  through  Lookin,  which  may  bring  risks.
2.  I'm  not  sure  if  Lookin's  code  could  cause  the  App  Store  to  reject  the  review.
3.  As  a  personal  amateur-maintained  debugging  tool,  its  stability  will  not  be  adequately  tested,  so  it  may  bring  potential  crash  risks  to  your  online  App.

---

You  can  certainly  integrate  Lookin  through  SPM.
But  according  to  the  configuration  of  LookinServer's Package.swift,  by  default,  it  will  only  be  compiled  under  Debug  conditions.

![screenshot-20231029-143456](https://github.com/hughkli/Lookin/assets/15059475/140d3084-eca6-4b98-a250-cd3c99dedaf4)
