### ISSUE TITLE
SwiftUI can not preview when installed Lookin

### ISSUE THREAD

**Issue by hjw6160602** [hughkli/Lookin#25]
Why I can not preview canvas when I use Lookin?
Write a SwiftUI View but can not use canvas to preview

**Comment by hughkli** [comment]
I don't know why, but any bugs related to SwiftUI are likely to occur.

Lookin has not made any adaptations for SwiftUI, and there are no plans to do so in the near future (because the author, me, doesn't understand SwiftUI).
