### ISSUE TITLE
1.0.3 compile failed

### ISSUE THREAD

**Issue by Bluelich** [hughkli/Lookin#26]
![image](https://github.com/hughkli/Lookin/assets/8563315/57f18b80-0020-4c26-8ad1-a6bbf9105d42)

**Comment by hughkli** [comment]
这么奇怪，我自己试着编译没问题呀。

你先重新 pod install 一下，如果仍然不行，截个图看看你的 podfile 里的 LookinShared 用的哪个版本?
![image](https://github.com/hughkli/Lookin/assets/15059475/5b2c769f-4919-4602-bba4-6f518687d7bb)
![image](https://github.com/hughkli/Lookin/assets/15059475/6ef2f1a0-485c-4095-bfb1-ecb00d40e1bf)

**Comment by Bluelich** [comment]
@hughkli  Fixed after `pod install`, thanks!
`LookinShared` version is `pod 'LookinShared', :git=>'https://github.com/QMUI/LookinServer.git', :branch => 'develop'`
