### ISSUE TITLE
1.0.4版本比较慢，定位图层的时候会卡死

### ISSUE THREAD

**Issue by dandan2009** [hughkli/Lookin#27]

**Comment by hughkli** [comment]
具体是什么操作会卡呢？展开图层列表的时候卡一下？还是选中图层时会卡一下？

**Comment by Xchn** [comment]
@hughkli LookinServer用的1.2.3版本，Lookin使用1.0.3版本不卡，1.0.4版本双击展开图层就有很大概率卡顿，鼠标就会一直转圈

**Comment by hughkli** [comment]
> @hughkli LookinServer用的1.2.3版本，Lookin使用1.0.3版本不卡，1.0.4版本双击展开图层就有很大概率卡顿，鼠标就会一直转圈

好吧，应该是因为我为了降低复杂度而删除了一些缓存策略，那我下个版本加回来吧，唉

**Comment by hughkli** [comment]
最新的 1.0.5 应该快多了，试试

**Comment by Xchn** [comment]
确实快了很多，感谢感谢🙏
