### ISSUE TITLE
测间距的字体能不能放大点

### ISSUE THREAD

**Issue by linconz** [hughkli/Lookin#28]
字体能不能放大点
<img width="289" alt="image" src="https://github.com/hughkli/Lookin/assets/2417911/a994b75e-b36f-41bc-a108-95b6be3c8f7b">

**Comment by linconz** [comment]
用的13的mbp，看着着实有点小

**Comment by hughkli** [comment]
可以，记个 todo，下个版本改改

**Comment by rakuyoMo** [comment]
有一些间距比较小，比如上下间距。然后会出现和左间距重叠在一起的情况。希望有机会也能优化一下

**Comment by hughkli** [comment]
> 有一些间距比较小，比如上下间距。然后会出现和左间距重叠在一起的情况。希望有机会也能优化一下

最新的 1.0.4 已经稍微做了一些优化缓解，你用了最新的 v1.0.4 后，这种情况仍然出现的很频繁吗？

**Comment by rakuyoMo** [comment]
> > 有一些间距比较小，比如上下间距。然后会出现和左间距重叠在一起的情况。希望有机会也能优化一下
> 
> 最新的 1.0.4 已经稍微做了一些优化缓解，你用了最新的 v1.0.4 后，这种情况仍然出现的很频繁吗？

1.0.4 确实好多啦！

**Comment by hughkli** [comment]
最新的 1.0.5 把字体稍微调大了一丁点，试试
