### ISSUE TITLE
iOS17上，图片渲染会崩溃,UIGraphicsBeginImageContext的适配会修改吗

### ISSUE THREAD

**Issue by Raul7777** [hughkli/Lookin#31]
在CALayer+LookinServer文件的渲染图像的方法上，比如lks_groupScreenshotWithLowQuality方法，会出现crash

Thread 1: "UIGraphicsBeginImageContext() failed to allocate CGBitampContext: size={1.7976931348623157e+308, 1.7976931348623157e+308}, scale=3.000000, bitmapInfo=0x2002. Use UIGraphicsImageRenderer to avoid this assert."

**Comment by hughkli** [comment]
最新的 LookinServer 版本应该已经修复了该问题，试试？
![screenshot-20231210-195750](https://github.com/hughkli/Lookin/assets/15059475/e6c29655-b007-4391-a4d2-6ec1adafa157)

**Comment by Raul7777** [comment]
更新到1.2.5可以了，感谢
