### ISSUE TITLE
Can you update the dependency of LookinShared to remote on the release branch？

### ISSUE THREAD

**Issue by Bluelich** [hughkli/Lookin#35]
Can you update the dependency of LookinShared to remote on the release branch？
I want to modify the source，but I found that  the dependency of LookinShared is commented, and the brach is  not a certain one. 
You can update it to a commit or one specified release branch.
```
https://github.com/hughkli/Lookin/blob/Release_1.0.6/Podfile#L11
```

**Comment by hughkli** [comment]
Thank you for your feedback. I have already modified the Podfile code for the 'Develop' and 'Release_1.0.6' branches of Lookin just now.
