### ISSUE TITLE
有计划支持visionOS吗

### ISSUE THREAD

**Issue by Mx-Iris** [hughkli/Lookin#38]
目前Xcode中不支持查看visionOS的层级结构，visionOS也一样使用UIKit，有适配的可能嘛

**Comment by hughkli** [comment]
暂时没有计划。

------
当 iOS App 以“Designed for iPad”模式运行时，Lookin 是可以正常使用的：
![20240318-112600](https://github.com/hughkli/Lookin/assets/15059475/76893db9-d547-496d-a1ef-5592ab61c97e)

但运行原生 VisionOS App 时，Lookin 确实无法使用，而且遇到了大量问题。
比如 VisionOS 上似乎压根没有 UIWindow 和 UIScreen 之类的概念？这导致 LookinServer SDK 大量的基础代码编译不过，而且我还不知道怎么解决😂。

又由于目前做 VisionOS 的人比较少，所以考虑下来，我个人暂时不会投入时间在 VisionOS 的适配上。

也许可以期待一下 Xcode 原生工具，或者看看有没有别的第三方工具。
