### ISSUE TITLE
更新到1.0.1后经常崩溃

### ISSUE THREAD

**Issue by Boompengp** [hughkli/Lookin#4]
M1 Pro   12.2.1
更新到最新版后很容易崩溃,复现路径是一直点击同一个View,直至它最深的子view显示出来,如果这时候有两个以上的子view,来回点击基本必崩.
跑了源码发现是某种情况下class为空导致,添加判空逻辑后没有崩过.希望作者百忙之中能早日修复这个问题
<img width="759" alt="image" src="https://user-images.githubusercontent.com/45331497/179887319-01f2a7ec-c487-4cf3-bdeb-37ba8d8322ae.png">

**Comment by hughkli** [comment]
好的，我这两天有空时研究一下，然后尽快发个新的版本

**Comment by ch3n0l1** [comment]
这个问题，最新版本依旧存在

**Comment by ch3n0l1** [comment]
该问题，Lookin更新至1.0.3后，依旧存在。

**Comment by hughkli** [comment]
> 该问题，Lookin更新至1.0.3后，依旧存在。

哈哈因为年代久远所以完全把这个事儿给忘了，我刚刚 push 了代码，把这个判空补上了（虽然还是没能复现出 Bug），跟着下个 Lookin 版本发，目测这个月吧。
