### ISSUE TITLE
无侵入模拟器断点接入功能是取消了吗？

### ISSUE THREAD

**Issue by ShihaoChen1** [hughkli/Lookin#8]
我记得之前有个在模拟器运行时，打断点就可以使用lookin的功能，现在我看官网和文档都没了，我在m1电脑上使用这个断点也不生效了，是把这个功能取消了吗？我觉得这个功能很棒啊。

**Comment by hughkli** [comment]
是的，因为不知道怎么弄：https://github.com/QMUI/LookinServer/issues/102#issuecomment-1202069145
